# TITAN_HOTFIX_V1_NOHUD.py
# Fixes:
# - Remove external HUD usage (no new UI)
# - Fix IndentationError in V1 Lite wrappers by rewriting them cleanly
# - Ensure snipping starts when launched from TitanCore (exec engine directly)
# - F11 = INTERVAL (AUTO SNAPSHOT). CAS only ` and Shift+F1.
# - V1 normal + V1 lite: NO naturalization
# - V1 IDN: maximal naturalization (best-effort, using existing localizer)
#
# NOTE: does NOT change semantics of STABLE/FREEZE/INTERVAL in engine logic.
# It only remaps hotkeys to desired functions and turns off extra CAS bindings.

from __future__ import annotations
import os, re, shutil, time, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
STAMP = time.strftime("%Y%m%d_%H%M%S")
BACKUP = ROOT / f"_backup_hotfix_v1_nohud_{STAMP}"

def log(msg: str):
    print(f"[HOTFIX] {msg}")

def read(p: Path) -> str:
    return p.read_text(encoding="utf-8", errors="replace")

def write(p: Path, s: str):
    p.write_text(s, encoding="utf-8", newline="\n")

def backup_files(paths):
    BACKUP.mkdir(parents=True, exist_ok=True)
    for p in paths:
        if p.exists():
            rel = p.relative_to(ROOT)
            dst = BACKUP / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, dst)
    log(f"Backup saved: {BACKUP.name}")

def find_v1_engine() -> Path:
    # Prefer engine file created by previous patchers
    cand = ROOT / "TitanMainV1_ENGINE.py"
    if cand.exists():
        return cand

    # Fallback: if TitanMainV1.py is original engine
    p = ROOT / "TitanMainV1.py"
    return p

WRAPPER_EXEC_TEMPLATE = r'''# Auto-generated by TITAN_HOTFIX_V1_NOHUD.py
# Runs engine DIRECTLY (no external HUD) -> snipping will work normally.
import os, sys
from pathlib import Path

def main():
    root = Path(__file__).resolve().parent
    target = "{target}"
    target_path = (root / target).resolve()
    if not target_path.exists():
        print("[WRAPPER] Target not found:", target_path)
        raise SystemExit(1)

    # set env flags without changing mode semantics
    os.environ.setdefault("PYTHONUTF8", "1")
    os.environ["TITAN_MODEL_LABEL"] = "{label}"
    os.environ["TITAN_MODEL_PRESET"] = "{preset}"

    # Optional: bypass game-hook gating during testing (recording tests)
    # This should NOT change capture modes; only prevents "no game" block.
    os.environ.setdefault("TITAN_GAME_OVERRIDE", "TEST")

    # naturalization policy
{nat_block}

    # exec into engine to preserve normal overlay/snipping behavior
    os.execv(sys.executable, [sys.executable, str(target_path)])

if __name__ == "__main__":
    main()
'''

def rewrite_wrappers(engine_name: str):
    # V1 normal (NO naturalize)
    write(ROOT / "TitanMainV1.py", WRAPPER_EXEC_TEMPLATE.format(
        target=engine_name,
        label="TITAN MAIN V1 (FAST) - NO NATURALIZE",
        preset="V1",
        nat_block='    os.environ["TITAN_DISABLE_NATURALIZE"] = "1"\n'
    ))
    # V1 Lite (NO naturalize, lightweight)
    write(ROOT / "TitanMainV1Lite.py", WRAPPER_EXEC_TEMPLATE.format(
        target=engine_name,
        label="TITAN MAIN V1 LITE (FAST+LIGHT) - NO NATURALIZE",
        preset="V1L",
        nat_block='    os.environ["TITAN_LITE"] = "1"\n    os.environ["TITAN_DISABLE_NATURALIZE"] = "1"\n'
    ))
    # V1 IDN (MAX naturalize)
    write(ROOT / "TitanMainV1_IDN.py", WRAPPER_EXEC_TEMPLATE.format(
        target=engine_name,
        label="TITAN MAIN V1 IDN (FAST) - NATURALIZE MAX",
        preset="V1_IDN",
        nat_block='    os.environ["TITAN_IDN_MODE"] = "1"\n    os.environ["TITAN_NATURALIZE_MAX"] = "1"\n'
    ))
    # V1 Lite IDN (MAX naturalize + lite)
    write(ROOT / "TitanMainV1Lite_IDN.py", WRAPPER_EXEC_TEMPLATE.format(
        target=engine_name,
        label="TITAN MAIN V1 LITE IDN (FAST+LIGHT) - NATURALIZE MAX",
        preset="V1L_IDN",
        nat_block='    os.environ["TITAN_LITE"] = "1"\n    os.environ["TITAN_IDN_MODE"] = "1"\n    os.environ["TITAN_NATURALIZE_MAX"] = "1"\n'
    ))

    log("Rewrote wrappers: V1 / V1Lite / V1_IDN / V1Lite_IDN (no HUD, no indentation issues)")

def patch_v1_engine_hotkeys_and_ms(engine_path: Path):
    if not engine_path.exists():
        log(f"Engine not found: {engine_path.name}")
        return

    s = read(engine_path)
    orig = s

    # ---------- 1) Ensure F11 is INTERVAL (AUTO), not CAS ----------
    # We do best-effort remap:
    # - Replace hotkey registration for 'ctrl+f11' to 'f11' (and keep ctrl+f11 if present)
    # - Remove any 'f11' mapping that toggles CAS
    lines = s.splitlines(True)
    out = []
    inserted_alias = False

    for line in lines:
        low = line.lower()

        # Remove any F11 CAS binding
        if "add_hotkey" in low and ("'f11'" in low or '"f11"' in low) and ("cas" in low or "capture all" in low or "toggle" in low):
            out.append("# [HOTFIX] removed: F11 CAS binding\n")
            continue

        # Keep CAS only on ` and Shift+F1
        if "add_hotkey" in low and ("cas" in low or "capture all" in low or "toggle_cas" in low or "cas_toggle" in low):
            if ("'`'" in line) or ('"`"' in line) or ("shift+f1" in low):
                out.append(line)
            else:
                out.append("# [HOTFIX] removed: extra CAS hotkey (CAS only on ` and Shift+F1)\n")
            continue

        # Promote ctrl+f11 (auto snapshot) to f11 and also keep ctrl+f11 as alias
        if "add_hotkey" in low and ("ctrl+f11" in low) and ("auto" in low or "interval" in low or "snapshot" in low):
            new_line = re.sub(r'([\'"])ctrl\+f11\1', r'\1f11\1', line, flags=re.IGNORECASE)
            out.append(new_line)
            # add alias ctrl+f11 (same handler)
            out.append(re.sub(r'([\'"])f11\1', r'\1ctrl+f11\1', new_line, flags=re.IGNORECASE))
            inserted_alias = True
            continue

        out.append(line)

    s = "".join(out)

    # Update shortcut help text if it exists
    s = s.replace("[CTRL+F11]", "[F11]")

    # ---------- 2) MS indicator internal (no new UI) ----------
    # Make sure engine has a global last-ms that can be used by its UI indicator.
    if "TITAN_LAST_TRANSLATION_MS" not in s:
        s = "TITAN_LAST_TRANSLATION_MS = 0  # [HOTFIX] updated each translation\n" + s

    # Try to update this global where PIPE log prints "{dt}ms"
    # Patterns we try:
    # - dt = ...; print(... f"... {dt}ms ...")
    # We'll inject assignment just before a PIPE print line.
    def inject_before_pipe(match: re.Match) -> str:
        return f'TITAN_LAST_TRANSLATION_MS = int({match.group(1)})  # [HOTFIX]\n' + match.group(0)

    # common: print(f"[PIPE] ... | {dt}ms | ...")
    s2 = re.sub(
        r'print\(\s*f[\'"]\[PIPE\][^\'"]*\{\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\}\s*ms',
        inject_before_pipe,
        s,
        count=1
    )
    if s2 == s:
        # fallback: any f-string containing {dt}ms without PIPE tag
        s2 = re.sub(
            r'print\(\s*f[\'"][^\'"]*\{\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\}\s*ms',
            inject_before_pipe,
            s,
            count=1
        )
    s = s2

    # Naturalization hook for V1_IDN only (best-effort):
    # Wrap output just before display/update if we find "translated =" patterns.
    # We will define a helper and inject usage into common variables.
    if "_titan_nat_idn" not in s:
        helper = r'''
def _titan_nat_idn(_text: str) -> str:
    # [HOTFIX] Naturalize only when IDN mode is ON
    try:
        import os as _os
        if _os.environ.get("TITAN_IDN_MODE", "0") != "1":
            return _text
        # maximal naturalization (best-effort)
        from TitanIndonesianLocalizer import naturalize as _nat
        return _nat(_text)
    except Exception:
        return _text
'''
        # insert helper near top (after imports best-effort)
        if "def _titan_nat_idn" not in s:
            s = re.sub(r'(\n)(\s*def\s+main\s*\(|\s*if\s+__name__\s*==)', helper + r'\n\2', s, count=1)

    # Try common assignments:
    # translated_text = ...
    # translated = ...
    # out_text = ...
    for var in ["translated_text", "translated", "out_text", "result_text", "final_text"]:
        s = re.sub(
            rf'^{var}\s*=\s*(.+)$',
            rf'{var} = \1\n{var} = _titan_nat_idn({var})  # [HOTFIX]',
            s,
            flags=re.MULTILINE
        )

    if s != orig:
        write(engine_path, s)
        log(f"Patched engine: {engine_path.name} (F11 interval, CAS keys, MS global, IDN naturalize hook)")
    else:
        log(f"No patch applied (patterns not found) in engine: {engine_path.name}")

def main():
    engine = find_v1_engine()

    # files to backup
    to_backup = [
        ROOT / "TitanMainV1.py",
        ROOT / "TitanMainV1Lite.py",
        ROOT / "TitanMainV1_IDN.py",
        ROOT / "TitanMainV1Lite_IDN.py",
        engine,
    ]
    backup_files(to_backup)

    # rewrite wrappers (fix indentation + remove HUD)
    rewrite_wrappers(engine.name)

    # patch engine for hotkeys + ms/naturalize hooks
    patch_v1_engine_hotkeys_and_ms(engine)

    print("\nDONE ✅")
    print("- Snipping harus muncul saat run dari TitanCore (karena wrapper exec langsung ke engine)")
    print("- F11 = INTERVAL (AUTO). CAS hanya ` dan Shift+F1.")
    print("- V1 & V1 Lite: NO naturalize. V1 IDN: naturalize MAX (best-effort).")
    print("\nTes:")
    print("  python TitanCore_V2.py -> pilih V1/V1Lite/V1_IDN")

if __name__ == "__main__":
    os.chdir(ROOT)
    main()
